global:
  scrape_interval: 60s 
  evaluation_interval: 60s 
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:
   - job_name: 'CARDANO-NODE' # To scrape data from the Cardano node
     scrape_interval: 2s
     static_configs:
       - targets: ['node-relay-1.local:12789']
       - targets: ['node-spo-1.local:12789']
