services:
  ogmios:
    image: cardanosolutions/ogmios:v6.0.0
    networks:
      mynet:
        aliases:
          - ogmios.local
    ports:
      - 1337:1337
    expose:
      - 1337
    volumes:
      - ${TESTNET_CONFIG}:/config
    command: [
      "--host", "0.0.0.0",
      "--node-socket", "/config/sockets/node-relay-1-socket/node.socket",
      "--node-config", "/config/configuration.yaml"
    ]
