services:
  genesis_spo:
    # image: congested-testnet-cli:latest
    build:
      context: ..
      dockerfile: Dockerfile
    command: ["sh", "-c", "hello"]
    # command: ["sh", "-c", "cardano-cli --help"]
    # ports:
    #   - "3000:3000"  
    #   - "12789:12789"  
    # environment:
    #   - ROOT=/data
    # volumes:
    #   - ../scripts/gen_testnet_conf.sh:/script
    #   - ./genesis_spo_data:/data
