services:
  node-spo-1:
    image: inputoutput/cardano-node:${CARDANO_TAG}
    networks:
       mynet:    
          aliases:
            - node-spo-1.local
    expose:
      - 3000
      - 6000
    volumes:
      - node-spo-1-db:/db
      - ../cardano-conf/node-spo1:/socket
      - ../cardano-conf:/config
    entrypoint: "cardano-node run \
                  --topology                        '/config/topology-spo-1.json' \
                  --database-path                   'db' \
                  --shelley-kes-key                 '/config/node-spo1/kes.skey' \
                  --shelley-vrf-key                 '/config/node-spo1/vrf.skey' \
                  --byron-delegation-certificate    '/config/node-spo1/byron-delegation.cert' \
                  --byron-signing-key               '/config/node-spo1/byron-delegate.key' \
                  --shelley-operational-certificate '/config/node-spo1/opcert.cert' \
                  --config                          '/config/configuration.yaml' \
                  --port                            '3000'"
