# FIXME this file was auto-generated by nixos-infect, it would be nice if
# it wasn't host dependant and was placed not in this repository

{ lib, ... }: {
  # This file was populated at runtime with the networking
  # details gathered from the active system.
  networking = {
    nameservers = [ "8.8.8.8"
 ];
    defaultGateway = "159.89.16.1";
    defaultGateway6 = {
      address = "";
      interface = "eth0";
    };
    dhcpcd.enable = false;
    usePredictableInterfaceNames = lib.mkForce false;
    interfaces = {
      eth0 = {
        ipv4.addresses = [
          { address="159.89.20.146"; prefixLength=20; }
        ];
        ipv6.addresses = [
          { address="fe80::48e9:22ff:fe21:53b1"; prefixLength=64; }
        ];
        ipv4.routes = [ { address = "159.89.16.1"; prefixLength = 32; } ];
        ipv6.routes = [ { address = ""; prefixLength = 128; } ];
      };
            eth1 = {
        ipv4.addresses = [
          { address="10.114.0.2"; prefixLength=20; }
        ];
        ipv6.addresses = [
          { address="fe80::10ea:f2ff:fe0d:4e23"; prefixLength=64; }
        ];
        };
    };
  };
  services.udev.extraRules = ''
    ATTR{address}=="4a:e9:22:21:53:b1", NAME="eth0"
    ATTR{address}=="12:ea:f2:0d:4e:23", NAME="eth1"
  '';
}
