# FIXME this file was auto-generated by nixos-infect, it would be nice if
# it wasn't host dependant and was placed not in this repository

{ lib, ... }: {
  # This file was populated at runtime with the networking
  # details gathered from the active system.
  networking = {
    nameservers = [
      "8.8.8.8"
    ];
    defaultGateway = "159.223.16.1";
    defaultGateway6 = {
      address = "";
      interface = "eth0";
    };
    dhcpcd.enable = false;
    usePredictableInterfaceNames = lib.mkForce false;
    interfaces = {
      eth0 = {
        ipv4.addresses = [
          { address = "159.223.18.248"; prefixLength = 20; }
        ];
        ipv6.addresses = [
          { address = "fe80::dc9a:f2ff:fed6:8b41"; prefixLength = 64; }
        ];
        ipv4.routes = [{ address = "159.223.16.1"; prefixLength = 32; }];
        ipv6.routes = [{ address = ""; prefixLength = 128; }];
      };
      eth1 = {
        ipv4.addresses = [
          { address = "10.114.0.2"; prefixLength = 20; }
        ];
        ipv6.addresses = [
          { address = "fe80::8420:a7ff:fedf:b4c8"; prefixLength = 64; }
        ];
      };
    };
  };
  services.udev.extraRules = ''
    ATTR{address}=="de:9a:f2:d6:8b:41", NAME="eth0"
    ATTR{address}=="86:20:a7:df:b4:c8", NAME="eth1"
  '';
}
